{
 "title": "API Health Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up{job='api-app'}" }
   ]
  },
  {
   "title": "Total Requests (1m Rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[1m]))",
     "legendFormat": "Req/sec"
    }
   ]
  },
  {
   "title": "HTTP Errors (4xx & 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{status_code=~'4..|5..'}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}